#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Tile all windows by default
yabai -m config layout bsp

# Mouse Settings
yabai -m config mouse_follows_focus   on
yabai -m config focus_follows_mouse   autofocus
# yabai -m config mouse_modifier        ctrl
yabai -m config mouse_action1         move
yabai -m config mouse_action2         resize
yabai -m mouse_drop_action            swap

# Window background opacity
yabai -m config window_opacity        on
yabai -m config active_window_opacity 0.98
yabai -m config normal_window_opacity 0.90

# New window placed right if vert split, bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config top_padding     3
yabai -m config bottom_padding  3
yabai -m config left_padding    3  
yabai -m config right_padding   3
yabai -m config window_gap      12

# rules
## Makes system preferences always floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$"    manage=off
yabai -m rule --add app="^Finder$"             manage=off
yabai -m rule --add app="^zoom.us$"            manage=off

yabai -m config external_bar all:24:0
