#!/bin/bash

# open iTerm
cmd - return : open -a "Ghostty" || true

# open Arc
cmd + shift - return : open -a "Zen" || true

# open Discord
shift + alt - d : open -a "Discord" || true

# Changing window focus
## Within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

## Between external displays
alt - n : yabai -m display --focus south
alt - m : yabai -m display --focus north

# Modifying the layout
## Rotate layout clockwise
shift + alt - r : yabai -m space --rotate 270

## Flip along y-axis
shift + alt - y : yabai -m space --mirror y-axis

## Flip along x-axis
shift + alt - x : yabai -m space --mirror x-axis

## Toggle window float
shift + alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# Modifying window size
## Maximise a window
ctrl + alt - m : yabai -m window --toggle zoom-fullscreen

# Balance out tree of windows (Occupy balanced area)
shift + alt - e : yabai -m space --balance

# Moving windows around
## Swap windows
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - h : yabai -m window --swap west
shift + alt - l : yabai -m window --swap east

## Move window and split
# ctrl + alt - j : yabai -m window --warp south
# ctrl + alt - k : yabai -m window --warp north
# ctrl + alt - h : yabai -m window --warp west
# ctrl + alt - l : yabai -m window --warp east

## Move window to external displays
shift + alt - n : yabai -m window --display south; yabai -m display --focus south;
shift + alt - m : yabai -m window --display north; yabai -m display --focus north;

## Move window to prev/next space
shift + alt - 0x21 : yabai -m window --space prev;
shift + alt - 0x1E : yabai -m window --space next;

# Move window to space number n
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;
shift + alt - 8 : yabai -m window --space 8;

# Resize window (In split)
## Move border to right (+ key)
shift + alt - 0x18 : yabai -m window --resize right:20:0 2> /dev/null || yabai -m window --resize left:20:0 2> /dev/null
## Move border to left (- key)
shift + alt - 0x1B : yabai -m window --resize right:-20:0 2> /dev/null || yabai -m window --resize left:-20:0 2> /dev/null
## Increase border up (+ key)
alt - 0x1B : yabai -m window --resize bottom:0:20 2> /dev/null || yabai -m window --resize top:0:20 2> /dev/null
## Decrease border down (- key)
alt - 0x18 : yabai -m window --resize bottom:0:-20 2> /dev/null || yabai -m window --resize top:0:-20 2> /dev/null

# Space Navigation
## Move to previous space (Loops around to the end)
ctrl + alt - h : yabai -m space --focus prev
## Move to next space (Loops around to the first)
ctrl + alt - l : yabai -m space --focus next
